//
//  NotificationDefine.h
//  Sigma
//
//  Created by 汤轶侬 on 16/7/25.
//  Copyright (c) 2016 Terence. All rights reserved.
//

#ifndef NotificationDefine_h
#define NotificationDefine_h

// all
#define REQUEST_DATA_ERROR @"REQUEST_DATA_ERROR"


// 热门
#define NOTI_POPULAR_QUESTION_DATA @"NOTI_POPULAR_QUESTION_DATA"
#define NOTI_POPULAR_VIDEO_DATA @"NOTI_POPULAR_VIDEO_DATA"
#define NOTI_POPULAR_RESOURCE_DATA @"NOTI_POPULAR_RESOURCE_DATA"

// 刷新通知
#define NOTI_END_LOADING @"NOTI_END_LOADING"

// 动态
#define NOTI_COMMUNITY_USER_DATA @"NOTI_COMMUNITY_USER_DATA"
#define NOTI_COMMUNITY_DYNAMICS_DATA @"NOTI_COMMUNITY_DYNAMICS_DATA"
#define NOTI_COMMUNITY_DYNAMIC_COMMENTS_DATA @"NOTI_COMMUNITY_DYNAMIC_COMMENTS_DATA"

// 登录注册
#define NOTI_SIGNIN_AUTH @"NOTI_SIGNIN_AUTH"
#define NOTI_SIGNIN_AUTH_ERRPR @"NOTI_SIGNIN_AUTH_ERRPR"
// 电话注册
#define NOTI_SIGNUP_PHONE @"NOTI_SIGNUP_PHONE"
#define NOTI_SIGNUP_PHONE_ERROR @"NOTI_SIGNUP_PHONE_ERROR"
// 邮箱注册
#define NOTI_SIGNUP_EMAIL @"NOTI_SIGNUP_EMAIL"
#define NOTI_SIGNUP_EMAIL_ERROR @"NOTI_SIGNUP_EMAIL_ERROR"
// 手机注册
#define NOTI_SIGNUP_CUSTOM @"NOTI_SIGNUP_CUSTOM"
#define NOTI_SIGNUP_CUSTOM_ERROR @"NOTI_SIGNUP_CUSTOM_ERROR"
// 用户信息
#define NOTI_SIGNUP_USER @"NOTI_SIGNUP_USER"
#define NOTI_SIGNUP_USER_ERROR @"NOTI_SIGNUP_USER_ERROR"
// 修改密码
#define NOTI_SIGNUP_PASS @"NOTI_SIGNUP_PASS"
#define NOTI_SIGNUP_PASS_ERROR @"NOTI_SIGNUP_PASS_ERROR"
// 修改用户信息
#define NOTI_SIGNUP_INFO @"NOTI_SIGNUP_INFO"
#define NOTI_SIGNUP_INFO_ERROR @"NOTI_SIGNUP_INFO_ERROR"

// 队伍
#define NOTI_TEAM_MESSAGES @"NOTI_TEAM_MESSAGES"
#define NOTI_TEAM_MESSAGES_ERROR @"NOTI_TEAM_MESSAGES_ERROR"
#define NOTI_TEAM_USER_MESSAGES @"NOTI_TEAM_USER_MESSAGES"
#define NOTI_TEAM_USER_MESSAGES_ERROR @"NOTI_TEAM_USER_MESSAGES_ERROR"
// 好友
//  添加好友
#define NOTI_TEAM_ADD_USER @"NOTI_TEAM_ADD_USER"
#define NOTI_TEAM_ADD_USER_ERROR @"NOTI_TEAM_ADD_USER_ERROR"
//  获取好友
#define NOTI_TEAM_FRIEND @"NOTI_TEAM_FRIEND"
#define NOTI_TEAM_FRIEND_ERROR @"NOTI_TEAM_FRIEND_ERROR"
// 获取队伍信息
#define NOTI_TEAM_GROUP @"NOTI_TEAM_GROUP"
#define NOTI_TEAM_GROUP_ERROR @"NOTI_TEAM_GROUP_ERROR"

// 七牛文件上传token获取
#define NOTI_QINIU_TOKEN @"NOTI_QINIU_TOKEN"
#define NOTI_QINIU_TOKEN_ERROR @"NOTI_QINIU_TOKEN_ERROR"

#define NOTI_TEAM_CREATE_TEAM @"NOTI_TEAM_CREATE_TEAM"
#define NOTI_TEAM_USER_ADD @"NOTI_TEAM_USER_ADD"

#define NOTI_TEAM_ADD_TEAM @"NOTI_TEAM_ADD_TEAM"
#define NOTI_TEAM_ADD_TEAM_ERROR @"NOTI_TEAM_ADD_TEAM_ERROR"


#endif /* NotificationDefine_h */
