//
//  NotificationDefine.h
//  Sigma
//
//  Created by 汤轶侬 on 16/7/25.
//  Copyright (c) 2016 Terence. All rights reserved.
//

#ifndef NotificationDefine_h
#define NotificationDefine_h

// all
#define REQUEST_DATA_ERROR @"REQUEST_DATA_ERROR"


// 热门
#define NOTI_POPULAR_QUESTION_DATA @"NOTI_POPULAR_QUESTION_DATA"
#define NOTI_POPULAR_VIDEO_DATA @"NOTI_POPULAR_VIDEO_DATA"
#define NOTI_POPULAR_RESOURCE_DATA @"NOTI_POPULAR_RESOURCE_DATA"

// 刷新通知
#define NOTI_END_LOADING @"NOTI_END_LOADING"

// 动态
#define NOTI_COMMUNITY_USER_DATA @"NOTI_COMMUNITY_USER_DATA"
#define NOTI_COMMUNITY_DYNAMICS_DATA @"NOTI_COMMUNITY_DYNAMICS_DATA"
#define NOTI_COMMUNITY_DYNAMIC_COMMENTS_DATA @"NOTI_COMMUNITY_DYNAMIC_COMMENTS_DATA"

// 资讯
#define NOTI_EINFORMATION_NEWSTYPE @"NOTI_EINFORMATION_NEWSTYPE"
#define NOTI_EINFORMATION_NEWSDETAIL @"NOTI_EINFORMATION_NEWSDETAIL"

// 登录注册
#define NOTI_SIGNIN_AUTH @"NOTI_SIGNIN_AUTH"
#define NOTI_SIGNIN_AUTH_ERRPR @"NOTI_SIGNIN_AUTH_ERRPR"




#endif /* NotificationDefine_h */
