//
//  NotificationDefine.h
//  Sigma
//
//  Created by 汤轶侬 on 16/7/25.
//  Copyright (c) 2016 Terence. All rights reserved.
//

#ifndef NotificationDefine_h
#define NotificationDefine_h

// all
#define REQUEST_DATA_ERROR @"REQUEST_DATA_ERROR"

// 热门
#define NOTI_POPULAR_QUESTION_DATA @"NOTI_POPULAR_QUESTION_DATA"
#define NOTI_POPULAR_VIDEO_DATA @"NOTI_POPULAR_VIDEO_DATA"
#define NOTI_POPULAR_RESOURCE_DATA @"NOTI_POPULAR_RESOURCE_DATA"


// 动态
#define NOTI_COMMUNITY_USER_DATA @"NOTI_COMMUNITY_USER_DATA"
#define NOTI_COMMUNITY_DYNAMICS_DATA @"NOTI_COMMUNITY_DYNAMICS_DATA"
#define NOTI_COMMUNITY_DYNAMIC_COMMENTS_DATA @"NOTI_COMMUNITY_DYNAMIC_COMMENTS_DATA"

//资源主界面
//资源
#define NOTI_RESOURCE_MAINPAGE_DATA @"NOTI_RESOURCE_MAINPAGE_DATA"
#define NOTI_RESOURCE_MAINPAGE_MAINQUEUE_DATA @"NOTI_RESOURCE_MAINPAGE_MAINQUEUE_DATA"

//资源具体描述界面
#define NOTI_DESCRIPTION_RESOURCE_DATA @"NOTI_DESCRIPTION_RESOURCE_DATA"

//category界面
#define CATEGORY_PAGE_DATA @"CATEGORY_PAGE_DATA"
//category界面返回主线程的通知
#define CATEGORY_PAGE_MAINQUEUE_DATA @"CATEGORY_PAGE_MAINQUEUE_DATA"

//course界面
//course主界面的通知
#define COURSE_MAINPAGE_DATA @"COURSE_MAINPAGE_DATA"
//course主界面返回主线程的通知
#define COURSE_MAINPAGE_MAINQUEUE_DATA @"COURSE_MAINPAGE_MAINQUEUE_DATA"




#endif /* NotificationDefine_h */
